export const strings = {
  auth: {
    loginTitle: "Entrar",
    registerTitle: "Criar conta",
    emailLabel: "E-mail",
    emailPlaceholder: "seu@email.com",
    passwordLabel: "Senha",
    passwordPlaceholder: "Mínimo 8 caracteres",
    loginButton: "Entrar",
    registerButton: "Criar conta",
    loginLink: "Já tem conta? Entre aqui",
    registerLink: "Não tem conta? Cadastre-se",
    errorInvalidCredentials: "E-mail ou senha incorretos",
    errorEmailInUse: "E-mail já cadastrado",
    errorWeakPassword: "A senha deve ter no mínimo 6 caracteres",
    errorInvalidEmail: "E-mail inválido",
    errorGeneric: "Erro ao autenticar. Tente novamente.",
    registerSuccess: "Conta criada! Faça login para continuar.",
    nameLabel: "Nome",
    namePlaceholder: "Seu nome completo",
    confirmPasswordLabel: "Confirmar senha",
    confirmPasswordPlaceholder: "Repita a senha",
    errorPasswordMismatch: "As senhas não coincidem",
  },

  home: {
    greeting: (name: string) => `Olá, ${name}!`,
    restDayTitle: "Dia de descanso",
    restDaySubtitle: "Aproveite para recuperar o corpo.",
    restDayBigTitle: "Descanso",
    restDayRecovery: "Recuperação é parte do treino! ",
    todayWorkoutTitle: "Treino de hoje",
    nextExercisesTitle: "Próximos exercícios",
    markCompleted: "Concluir treino",
    markSkipped: "Pular treino",
    startWorkout: "Iniciar treino",
    noSheetTitle: "Sem plano de treino",
    noSheetSubtitle: "Crie seu plano na aba Treinos.",
    noSheetCta: "Criar plano",
    loadingToday: "Carregando treino de hoje…",
    errorRetry: "Tentar novamente",
    errorTitle: "Não foi possível carregar",
    statStreak: "Sequência",
    statWeek: "Esta semana",
    statWeekUnit: "concluídos",
    statTotal: "Total",
    statDays: "dias",
    statSessions: "sessões",
    todayIsRest: "Hoje é dia de descanso",
    completedBadge: "Concluído",
    skippedBadge: "Pulado",
    partialBadge: "Parcial",
    noExercises: "Nenhum exercício hoje",
    calendarNoSheet: "Crie um plano de treino para ver o calendário.",
    recentSessions: "Sessões Recentes",
    viewAll: "Ver todas",
    seriesCount: (n: number) => `${n} série${n !== 1 ? "s" : ""}`,
    exerciseCount: (n: number) => `${n} exercício${n !== 1 ? "s" : ""}`,
    moreExercises: (n: number) => `+${n} exercício${n !== 1 ? "s" : ""}`,
    todayDayLabel: (day: string) => day,
    muscleGroupsTitle: (groups: string) => groups,
    startWorkoutShort: "Iniciar",
    dayWorkoutTitle: (day: string) => `Treino de ${day}`,
  },

  sessionHistory: {
    title: "Histórico do Treino",
    plannedWorkout: "Treino planejado",
    recordedSets: "Séries registradas",
    noRecords: "Nenhuma série registrada nesta sessão.",
    statusCompleted: "Concluído",
    statusSkipped: "Pulado",
    statusPartial: "Parcial",
    statusPending: "Pendente",
    weightReps: (w: number, r: number) => `${w} kg × ${r} rep`,
    restLabel: (s: number) => `${s}s descanso`,
    missedDayTitle: "Dia perdido",
    missedDaySubtitle: "Nenhum treino foi registrado nesse dia.",
  },

  trainingPlan: {
    title: "Meu Plano de Treino",
    titleSub: "",
    titleMain: "Plano de Treino",
    createSheet: "Criar plano",
    noSheetTitle: "Nenhum plano criado",
    noSheetSubtitle: "Crie seu plano de treino para começar.",
    dayTraining: "Treino",
    dayRest: "Descanso",
    toggleToTraining: "Definir como treino",
    toggleToRest: "Definir como descanso",
    monday: "Segunda-feira",
    tuesday: "Terça-feira",
    wednesday: "Quarta-feira",
    thursday: "Quinta-feira",
    friday: "Sexta-feira",
    saturday: "Sábado",
    sunday: "Domingo",
    mondayShort: "SEG",
    tuesdayShort: "TER",
    wednesdayShort: "QUA",
    thursdayShort: "QUI",
    fridayShort: "SEX",
    saturdayShort: "SÁB",
    sundayShort: "DOM",
    sectionMuscles: "Grupos Musculares",
    sectionDays: "Dias da Semana",
    summaryTrainingDays: (n: number) =>
      `${n} dia${n !== 1 ? "s" : ""} de treino`,
    summaryRestDays: (n: number) => `${n} dia${n !== 1 ? "s" : ""} de descanso`,
    todayBadge: "Hoje",
    todayLabel: "HOJE",
    noExercisesDay: "Nenhum exercício",
    dayBreadcrumb: "Plano de treino",
    statExercises: "exercícios",
    statSeries: "séries",
    startWorkout: "Iniciar Treino",
    dayMetaCount: (count: number, totalSeries: number) =>
      `${count} exercício${count !== 1 ? "s" : ""} · ${totalSeries} série${totalSeries !== 1 ? "s" : ""}`,
    seriesFooter: {
      total: (n: number) => `${n} série${n !== 1 ? "s" : ""} totais`,
      warmUp: (n: number) => `${n} aquecimento`,
      adjustment: (n: number) => `${n} adaptação`,
      working: (n: number) => `${n} trabalho`,
    },
    exercisesCount: (n: number) => `${n} exercício${n !== 1 ? "s" : ""}`,
  },

  exercises: {
    title: "Exercícios",
    addButton: "Adicionar exercício",
    editButton: "Editar",
    deleteButton: "Excluir",
    saveButton: "Salvar",
    cancelButton: "Cancelar",
    nameLabel: "Nome do exercício",
    namePlaceholder: "Ex: Supino reto",
    muscleGroupLabel: "Grupo muscular",
    seriesLabel: "Séries",
    addSeriesButton: "Adicionar série",
    emptyTitle: "Nenhum exercício",
    emptySubtitle: "Adicione exercícios a este dia de treino.",
    deleteConfirm: "Excluir exercício?",
    deleteConfirmBody: (name: string) =>
      `"${name}" será removido permanentemente do dia de treino.`,
    seriesType: {
      "warm-up": "Aquecimento",
      adjustment: "Adaptação",
      working: "Trabalho",
    },
    muscleGroups: {
      Peito: "Peito",
      Tríceps: "Tríceps",
      Costas: "Costas",
      Bíceps: "Bíceps",
      Ombros: "Ombros",
      Abdômen: "Abdômen",
      Perna: "Perna",
      Glúteo: "Glúteo",
      Trapézio: "Trapézio",
      Antebraço: "Antebraço",
      Panturrilha: "Panturrilha",
    },
  },

  workout: {
    title: "Treinar",
    titleFull: "Treinar Agora",
    noSessionTitle: "Sem treino hoje",
    noSessionSubtitle: "Não há treino programado para hoje.",
    restDayTitle: "Dia de descanso",
    completedTitle: "Treino de hoje concluído!",
    skippedTitle: "Treino pulado",
    readOnlyNotice: "Este treino já foi finalizado.",
    finishSession: "Finalizar treino",
    skipSession: "Pular treino",
    addSet: "Registrar série",
    editSet: "Editar série",
    deleteSet: "Excluir série",
    weightLabel: "Carga (kg)",
    repsLabel: "Repetições",
    restTimeLabel: "Descanso (s)",
    seriesOrderLabel: "Ordem",
    loggedSetsTitle: "Séries registradas",
    emptyLogTitle: "Nenhuma série registrada",
    loadingSession: "Carregando sessão…",
    // Tab view
    tabIniciar: "Iniciar Treino",
    tabHistorico: (n: number) => `Histórico (${n})`,
    selectDayTitle: "Selecionar dia para treinar",
    startCta: (day: string) => `Iniciar: ${day}`,
    noSheetText: "Configure seu plano de treino para começar.",
    noHistory: "Nenhum treino registrado ainda.",
    exerciseCount: (n: number) => `${n} ex`,
    // Session view
    inProgress: "Em andamento",
    goalLabel: (reps: number) => `Meta: ${reps} reps`,
    goalRangeLabel: (min: number, max: number) => `Meta: ${min} a ${max} reps`,
    seriesLabel: (n: number) => `Série ${n}`,
    progressCounter: (done: number, total: number) => `${done}/${total}`,
    skipBtn: "Pular",
    concludeBtn: (done: number, total: number) => `Concluir (${done}/${total})`,
    weightShort: "Peso (kg)",
    repsShort: "Reps",
    restShort: "Descanso (s)",
    // History status labels
    statusRecorded: "Concluído",
    statusSkipped: "Pulado",
    statusPending: "Pendente",
  },

  progression: {
    title: "Progresso",
    titleMain: "Perfil",
    summaryTitle: "Resumo",
    currentStreak: "Sequência atual",
    longestStreak: "Maior sequência",
    totalSessions: "Total de treinos",
    personalRecords: "Recordes pessoais",
    chartTitle: "Evolução de carga",
    selectExercise: "Selecione um exercício",
    selectExerciseHint:
      "Selecione um exercício acima para ver a evolução de carga",
    noDataTitle: "Sem dados ainda",
    noDataSubtitle: "Complete alguns treinos para ver sua evolução.",
    noExercisesWithData: "Nenhum exercício com histórico ainda.",
    weeklyActivityTitle: "Atividade Semanal",
    chargeProgressionTitle: "Progressão de Carga",
    muscleFocusTitle: "Foco Muscular",
    statWorkouts: "treinos",
    statSeries: "séries",
    statStreakDays: "dias consecutivos",
    prLabel: (weight: number, reps: number, date: string) =>
      `PR: ${weight} kg × ${reps} reps (em ${date})`,
    improvement: (pct: number) => `+${pct.toFixed(1)}%`,
    seriesUnit: (n: number) => `${n} série${n !== 1 ? "s" : ""}`,
    days: (n: number) => `${n} dia${n !== 1 ? "s" : ""}`,
    monthlyHistoryTitle: "Histórico Mensal",
  },

  nav: {
    home: "Início",
    trainingPlan: "Plano",
    workout: "Treinar",
    progression: "Perfil",
  },

  common: {
    loading: "Carregando…",
    error: "Algo deu errado.",
    retry: "Tentar novamente",
    confirm: "Confirmar",
    cancel: "Cancelar",
    save: "Salvar",
    delete: "Excluir",
    edit: "Editar",
    close: "Fechar",
    back: "Voltar",
    yes: "Sim",
    no: "Não",
    defaultUserName: "Atleta",
    ariaNotifications: "Notificações",
    ariaLogout: "Sair",
    ariaViewExercises: "Ver exercícios",
    ariaEditExercise: "Editar exercício",
    ariaDeleteExercise: "Excluir exercício",
    ariaEditSet: "Editar série",
    ariaDeleteSet: "Excluir série",
    ariaEditRecords: "Editar séries registradas",
    ariaConfirmEdit: "Confirmar edição",
    ariaCancelEdit: "Cancelar edição",
    ariaRemoveSet: "Remover série",
    ariaGoBack: "Voltar",
  },

  exerciseSearch: {
    placeholder: "Buscar exercício...",
    initialState: "Digite para buscar exercícios",
    noResults: "Nenhum exercício encontrado",
    error: "Erro ao buscar exercícios",
    retry: "Tentar novamente",
  },

  csvImport: {
    downloadTemplate: "Baixar template",
    chooseFile: "Escolher arquivo",
    uploadButton: "Enviar arquivo",
    success: "exercícios importados com sucesso",
    errorTitle: "Erro ao importar CSV",
    instruction: "Após importar configure as séries manualmente",
  },

  videoTips: {
    sectionLabel: "📹 Vídeo e Dicas",
    videoTab: "Vídeo",
    tipsTab: "Dicas",
    noVideo: "Sem vídeo disponível",
    noTips: "Sem dicas disponíveis",
    watchLink: "Buscar tutorial no YouTube",
  },

  restTimer: {
    fieldLabel: "Tempo de descanso",
    fieldHint: (s: number) => {
      const m = Math.floor(s / 60);
      const sec = s % 60;
      return `= ${String(m).padStart(2, "0")}:${String(sec).padStart(2, "0")}`;
    },
    fieldPlaceholder: "Segundos (ex: 90)",
    buttonIdle: "Descanso",
    buttonCancel: "Cancelar descanso",
    finishedMessage: "Pode continuar!",
  },
} as const;

export const MUSCLE_GROUPS = [
  "Todos",
  "Peito",
  "Costas",
  "Ombros",
  "Bíceps",
  "Tríceps",
  "Perna",
  "Glúteo",
  "Abdômen",
  "Trapézio",
  "Antebraço",
  "Panturrilha",
] as const;
